const db = require('../database/init');
const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { logAudit } = require('../services/auditService');

const generateExcelReport = async (req, res) => {
    const shopId = req.user.active_shop_id;
    const { type = 'Billing', from, to } = req.query;

    const shop = db.prepare(`SELECT * FROM shops WHERE id = ?`).get(shopId) || { shop_name: 'Shop System', currency: '₹' };

    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet(type);

    // Title Block
    sheet.mergeCells('A1', 'G1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = shop.shop_name.toUpperCase();
    titleCell.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FFFFFFFF' } };
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1A1A1A' } };
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

    sheet.mergeCells('A2', 'G2');
    const subTitleCell = sheet.getCell('A2');
    subTitleCell.value = `${type.toUpperCase()} REPORT ${from && to ? `(${from} to ${to})` : ''}`;
    subTitleCell.font = { name: 'Arial', size: 11, italic: true };
    subTitleCell.alignment = { horizontal: 'center' };

    sheet.addRow([`Generated On: ${new Date().toLocaleString()}`, `Generated By: ${req.user.name || req.user.username}`]);
    sheet.addRow([]);

    let dateWhere = '';
    const params = [shopId];
    if (from) { dateWhere += ` AND date(created_at) >= date(?)`; params.push(from); }
    if (to) { dateWhere += ` AND date(created_at) <= date(?)`; params.push(to); }

    // Report Type Handlers
    if (type === 'Inventory' || type === 'Stock Value') {
        const headerRow = sheet.addRow(['Item Name', 'Category', 'Unit', 'Buy Price', 'Selling Price', 'Current Stock', 'Stock Value']);
        styleHeaderRow(headerRow);

        const items = db.prepare(`SELECT * FROM items WHERE shop_id = ? AND status = 'active' ORDER BY name ASC`).all(shopId);
        let totalVal = 0;
        items.forEach(i => {
            const val = (i.buy_price || 0) * (i.stock || 0);
            totalVal += val;
            sheet.addRow([i.name, i.category || 'General', i.unit || 'Pcs', i.buy_price, i.selling_price, i.stock, val]);
        });
        sheet.addRow([]);
        const totalRow = sheet.addRow(['', '', '', '', '', 'Total Inventory Value:', totalVal]);
        totalRow.font = { bold: true };
    } else if (type === 'Customer') {
        const headerRow = sheet.addRow(['Customer Name', 'Phone', 'Email', 'GST', 'Total Bills', 'Total Spent', 'Registered Date']);
        styleHeaderRow(headerRow);

        const customers = db.prepare(`SELECT * FROM customers WHERE shop_id = ? ORDER BY name ASC`).all(shopId);
        customers.forEach(c => {
            const billStats = db.prepare(`SELECT COUNT(*) as count, COALESCE(SUM(total), 0) as totalSpent FROM bills WHERE shop_id = ? AND customer_phone = ?`).get(shopId, c.phone);
            sheet.addRow([c.name, c.phone || 'N/A', c.email || 'N/A', c.gst || 'N/A', billStats ? billStats.count : 0, billStats ? billStats.totalSpent : 0, c.created_at]);
        });
    } else if (type === 'Financial' || type === 'Profit') {
        const headerRow = sheet.addRow(['Date', 'Bill Number', 'Customer', 'Revenue', 'Est. Cost', 'Gross Profit']);
        styleHeaderRow(headerRow);

        const bills = db.prepare(`SELECT * FROM bills WHERE shop_id = ? ${dateWhere} ORDER BY created_at DESC`).all(...params);
        let totalRev = 0, totalCost = 0;

        bills.forEach(b => {
            const bItems = db.prepare(`SELECT bi.*, i.buy_price FROM bill_items bi LEFT JOIN items i ON bi.item_id = i.id WHERE bi.bill_id = ?`).all(b.id);
            let cost = 0;
            bItems.forEach(bi => { cost += (bi.buy_price || 0) * bi.qty; });
            const profit = b.total - cost;

            totalRev += b.total;
            totalCost += cost;

            sheet.addRow([new Date(b.created_at).toLocaleDateString(), b.bill_number, b.customer_name || 'Walk-in', b.total, cost, profit]);
        });

        sheet.addRow([]);
        const summaryRow = sheet.addRow(['TOTALS', '', '', totalRev, totalCost, totalRev - totalCost]);
        summaryRow.font = { bold: true };
    } else if (type === 'Low Stock') {
        const shopInfo = db.prepare(`SELECT low_stock_alert FROM shops WHERE id = ?`).get(shopId);
        const threshold = shopInfo ? shopInfo.low_stock_alert : 5;

        const headerRow = sheet.addRow(['Item Name', 'Category', 'Unit', 'Current Stock', 'Low Stock Alert Threshold', 'Status']);
        styleHeaderRow(headerRow);

        const items = db.prepare(`SELECT * FROM items WHERE shop_id = ? AND status = 'active' AND stock <= ? ORDER BY stock ASC`).all(shopId, threshold);
        items.forEach(i => {
            sheet.addRow([i.name, i.category, i.unit, i.stock, threshold, 'REORDER REQUIRED']);
        });
    } else if (type === 'Stock Report' || type === 'Stock Logs') {
        const headerRow = sheet.addRow(['Date & Time', 'Item Name', 'Movement Type', 'Quantity', 'Reason / Supplier', 'Notes', 'User']);
        styleHeaderRow(headerRow);

        const logs = db.prepare(`SELECT sl.*, u.name as user_name FROM stock_logs sl LEFT JOIN users u ON sl.user_id = u.id WHERE sl.shop_id = ? ORDER BY sl.created_at DESC`).all(shopId);
        logs.forEach(l => {
            sheet.addRow([new Date(l.created_at).toLocaleString(), l.item_name, l.type.toUpperCase(), l.quantity, l.supplier || l.reason || 'N/A', l.notes || '', l.user_name || 'System']);
        });
    } else {
        // Default: Billing / Sales Report
        const headerRow = sheet.addRow(['Bill Number', 'Date', 'Customer Name', 'Customer Phone', 'Payment Mode', 'Subtotal', 'Tax', 'Discount', 'Total Amount']);
        styleHeaderRow(headerRow);

        const bills = db.prepare(`SELECT * FROM bills WHERE shop_id = ? ${dateWhere} ORDER BY created_at DESC`).all(...params);
        let grandTotal = 0;
        bills.forEach(b => {
            grandTotal += b.total;
            sheet.addRow([b.bill_number, new Date(b.created_at).toLocaleString(), b.customer_name || 'Walk-in', b.customer_phone || '', b.payment_mode || 'Cash', b.subtotal, b.tax, b.discount, b.total]);
        });

        sheet.addRow([]);
        const totalRow = sheet.addRow(['TOTAL SALES', '', '', '', '', '', '', '', grandTotal]);
        totalRow.font = { bold: true };
    }

    // Auto fit column widths
    sheet.columns.forEach(column => {
        let maxLen = 12;
        column.eachCell({ includeEmpty: true }, cell => {
            const valStr = cell.value ? cell.value.toString() : '';
            if (valStr.length > maxLen) maxLen = Math.min(valStr.length, 40);
        });
        column.width = maxLen + 3;
    });

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename=${type.replace(/\s+/g, '_')}_Report.xlsx`);

    await workbook.xlsx.write(res);
    res.end();

    logAudit(shopId, req.user.id, 'Report Download', `Downloaded Excel ${type} Report`);
};

function styleHeaderRow(row) {
    row.eachCell(cell => {
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF333333' } };
        cell.alignment = { horizontal: 'left', vertical: 'middle' };
    });
}

const generatePDFReport = (req, res) => {
    const shopId = req.user.active_shop_id;
    const { type = 'Billing', from, to } = req.query;

    const shop = db.prepare(`SELECT * FROM shops WHERE id = ?`).get(shopId) || { shop_name: 'Shop System', currency: '₹' };

    const doc = new PDFDocument({ margin: 40, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${type.replace(/\s+/g, '_')}_Report.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(20).text(shop.shop_name, { align: 'center' });
    doc.fontSize(12).text(`${type.toUpperCase()} REPORT`, { align: 'center' });
    if (from && to) doc.fontSize(10).text(`Period: ${from} to ${to}`, { align: 'center' });
    doc.fontSize(9).text(`Generated: ${new Date().toLocaleString()} | User: ${req.user.name || req.user.username}`, { align: 'center' });
    doc.moveDown(1.5);

    doc.moveTo(40, doc.y).lineTo(550, doc.y).stroke('#000000');
    doc.moveDown(1);

    let dateWhere = '';
    const params = [shopId];
    if (from) { dateWhere += ` AND date(created_at) >= date(?)`; params.push(from); }
    if (to) { dateWhere += ` AND date(created_at) <= date(?)`; params.push(to); }

    if (type === 'Inventory') {
        const items = db.prepare(`SELECT * FROM items WHERE shop_id = ? AND status = 'active' ORDER BY name ASC`).all(shopId);
        doc.fontSize(10).font('Helvetica-Bold');
        doc.text('Item Name', 40, doc.y, { width: 180 });
        doc.text('Category', 220, doc.y - 12, { width: 100 });
        doc.text('Price', 330, doc.y - 12, { width: 80, align: 'right' });
        doc.text('Stock', 420, doc.y - 12, { width: 80, align: 'right' });
        doc.moveDown(0.5);
        doc.font('Helvetica');

        items.forEach(i => {
            if (doc.y > 750) doc.addPage();
            doc.fontSize(9).text(i.name, 40, doc.y, { width: 180 });
            doc.text(i.category || 'General', 220, doc.y - 10, { width: 100 });
            doc.text(`${shop.currency}${i.selling_price.toFixed(2)}`, 330, doc.y - 10, { width: 80, align: 'right' });
            doc.text(`${i.stock} ${i.unit}`, 420, doc.y - 10, { width: 80, align: 'right' });
            doc.moveDown(0.3);
        });
    } else {
        // Billing Default
        const bills = db.prepare(`SELECT * FROM bills WHERE shop_id = ? ${dateWhere} ORDER BY created_at DESC`).all(...params);
        doc.fontSize(10).font('Helvetica-Bold');
        doc.text('Bill #', 40, doc.y, { width: 80 });
        doc.text('Date', 120, doc.y - 12, { width: 100 });
        doc.text('Customer', 220, doc.y - 12, { width: 150 });
        doc.text('Total', 420, doc.y - 12, { width: 100, align: 'right' });
        doc.moveDown(0.5);
        doc.font('Helvetica');

        let grandTotal = 0;
        bills.forEach(b => {
            if (doc.y > 750) doc.addPage();
            grandTotal += b.total;
            doc.fontSize(9).text(b.bill_number, 40, doc.y, { width: 80 });
            doc.text(new Date(b.created_at).toLocaleDateString(), 120, doc.y - 10, { width: 100 });
            doc.text(b.customer_name || 'Walk-in', 220, doc.y - 10, { width: 150 });
            doc.text(`${shop.currency}${b.total.toFixed(2)}`, 420, doc.y - 10, { width: 100, align: 'right' });
            doc.moveDown(0.3);
        });

        doc.moveDown(1);
        doc.font('Helvetica-Bold').fontSize(11).text(`Grand Total: ${shop.currency}${grandTotal.toFixed(2)}`, 350, doc.y, { align: 'right' });
    }

    doc.end();
    logAudit(shopId, req.user.id, 'Report Download', `Downloaded PDF ${type} Report`);
};

module.exports = {
    generateExcelReport,
    generatePDFReport
};
